### ISSUE TITLE
java.lang.UnsatisfiedLinkError on BeagleBone running Ubuntu

### ISSUE THREAD

**Issue by rstoeck** [usb4java/usb4java#30]
Hello,

We are using usb4java-1.0.0.jar to access USB devices on our various Linux distributions. The library works fine on our 32-bit Linux Mint distro and BeagleBone Angstrom distribution.

However, we are trying to run the BeagleBone with Ubuntu (13.0.4). When we run our code, we get the following error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/usb4java7866977171456936988.tmp/libusb4java.so: /tmp/usb4java7866977171456936988.tmp/libusb4java.so: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    . . . .

Would you have any idea why this might be happening?

Do you have any suggestions on how to fix it? Or any potential work-arounds?

Thanks for any assistance you can give.

-Rob

**Comment by cjritola** [comment]
Had same issue in another project under BeagleBone armhf. Refactored against usb4java-1.2.0 artifact and the issue resolved.

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
