### ISSUE TITLE
Bulk write to Vx810 Pinpad

### ISSUE THREAD

**Issue by pgiorgi** [usb4java/usb4java#37]
I have a problem with this exception in Windows ( in linux wors fine )
USB error 5: Transfer error on bulk endpoint: Entity not found
This exception is produced by async Submint of UsbIrp in output endpoint. The data is only a 0x15 ( one byte)
I cant get more infromation it to try to resolv.
When I use a for Exmaple Ingenico IPP320 pinpad( only change the input endpoint number ) it works in linux and windows. 
In linux for booth device I use de Winusb driver instaled using  zadig (WinUSB (v6.1.7600.16385))
Could you help me?
Thanks

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
