### ISSUE TITLE
javax.usb.UsbPlatformException: USB error 12

### ISSUE THREAD

**Issue by freefire4547** [usb4java/usb4java#38]
when I am running I am getting error
javax.usb.UsbPlatformException: USB error 12: Unable to claim interface: Operation not supported or unimplemented on this platform
I have successfully run all high level examples.But when I run UsbInterface.claim() function I am getting this error.Usb devices that I have used is Webcam (made in china) ,HP Scanner,ZTE Modem.I have tested all three drivers WinUSB, libusb-win32 and libusbK  but all give same error.

**Comment by sibiarunachalam** [comment]
I encountered the same problem.
Have you resolved this one?
