### ISSUE TITLE
usb4java 1.2.0 on OS X 10.6

### ISSUE THREAD

**Issue by scytacki** [usb4java/usb4java#41]
I've been having issues with usb4java 1.2.0 on OS X 10.6.
When I run the simple device listing example it returns no error and no list of devices.

After I recompiled libusb4java with libusb installed with `brew install libusb`, now it works.

Any on ideas on where I should look for differences between what is bundled in libusb4java-1.2.0-osx-x86_64.jar and my locally compiled version? Perhaps 1.2.0 was compiled with an older libusb? or Perhaps it was compiled on 10.7 or higher, so the libusb is not compatible with 10.6?

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
