### ISSUE TITLE
Connection crash on Windows 7

### ISSUE THREAD

**Issue by michaelDomingues** [usb4java/usb4java#42]
I'm using v1.0.0 and connection to devices in Windows7 is messy, this means, I can't connect most of the times. I need to force connection several times to be able to use the device. Do you think this is a bug or something related to the device and driver ?
In windows 8 all works well.

Thanks a lot

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
