### ISSUE TITLE
Device connected to USB3 port not contained in device list

### ISSUE THREAD

**Issue by folkfreund** [usb4java/usb4java#44]
The low level function LibUsb.getDeviceList works well for normal USB ports, but if the device is connected to a high speed port of my laptop, it is not contained in the device list.

I'm using WinUSB driver on Win7. The device shows up in Windows device manager list.

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
