### ISSUE TITLE
USB error 7: Unable to read data: Operation timed out

### ISSUE THREAD

**Issue by Ravikiran16218** [usb4java/usb4java#61]
Hello all here im trying to read and write some bytes  to the device. Im able to write on device but when it comes to reading part it is throwing some exception as
--> Exception in thread "main" org.usb4java.LibUsbException: USB error 7: Unable to read data: Operation timed out
	at readwrite1.read(readwrite1.java:109)
	at readwrite1.main(readwrite1.java:160)
Please help me to solve this issue.
The code as follows.
----------------------------------------------------------------------------------------------------------------------------------
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.IntBuffer;
import org.usb4java.BufferUtils;
import org.usb4java.DeviceHandle;
import org.usb4java.LibUsb;
import org.usb4java.LibUsbException;
/**
* Demonstrates how to do synchronous bulk transfers. This demo sends some
* hardcoded data to an Device and receives some
* data from it.
*/
public class readwrite1
{
/** Bytes for a CONNECT ADB message header. */
private static final byte[] CONNECT_HEADER = new byte[] { 0x43, 0x4E, 0x58,
0x4E, 0x00, 0x00, 0x00, 0x01, 0x00, 0x10, 0x00, 0x00, 0x17, 0x00, 0x00,
0x00, 0x42, 0x06, 0x00, 0x00, (byte) 0xBC, (byte) 0xB1, (byte) 0xA7,
(byte) 0xB1 };
/** Bytes for a CONNECT ADB message body. */
private static final byte[] CONNECT_BODY = new byte[] { 0x68, 0x6F, 0x73,
0x74, 0x3A, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x3A, 0x41,
0x44, 0x42, 0x20, 0x44, 0x65, 0x6D, 0x6F, 0x00 };
/** The vendor ID of the device. */
private static final short VENDOR_ID = 0x03eb;
/** The vendor ID of the device */
private static final short PRODUCT_ID = 0x6124;
/** The ADB interface number of the Sdevice */
private static final byte INTERFACE = 1;
private static final byte interfaceNum = 1;

/** The ADB input endpoint of thedevice */
private static final byte IN_ENDPOINT = (byte) 0x83;
/** The ADB output endpoint of the device */
private static final byte OUT_ENDPOINT = 0x01;
/** The communication timeout in milliseconds. */
private static final int TIMEOUT = 5000;
/**
* Writes some data to the device.
* The data to send to the device.
*/
public static void write(DeviceHandle handle, byte[] data)
{

ByteBuffer buffer = BufferUtils.allocateByteBuffer(data.length);
System.out.println("data11-->"+data);
System.out.println("CONNECT_BODY-->"+CONNECT_BODY);
System.out.println("CONNECT_HEADER-->"+CONNECT_HEADER);

buffer.put(data);
IntBuffer transferred = BufferUtils.allocateIntBuffer();
int result = LibUsb.bulkTransfer(handle, OUT_ENDPOINT, buffer,
transferred, TIMEOUT);
if (result != LibUsb.SUCCESS)
{
throw new LibUsbException("Unable to send data", result);
}
System.out.println(transferred.get() + " bytes sent to device");
}
/**
* Reads some data from the device.
* The number of bytes to read from the device.
* @return The read data.
*/
public static ByteBuffer read(DeviceHandle handle, int size)
{
    System.out.println("SSSS");
ByteBuffer buffer = BufferUtils.allocateByteBuffer(size).order(
ByteOrder.LITTLE_ENDIAN);
System.out.println("buffer++++++"+buffer);
IntBuffer transferred = BufferUtils.allocateIntBuffer();
System.out.println("transferred++++++"+transferred);

int result = LibUsb.bulkTransfer(handle, IN_ENDPOINT, buffer,
transferred, TIMEOUT);
int result1 = LibUsb.attachKernelDriver(handle, IN_ENDPOINT);
System.out.println("result1-->"+result1);

System.out.println("srsult"+result);
System.out.println("SSSSSSS");
if (result != LibUsb.SUCCESS)
{
throw new LibUsbException("Unable to read data", result);
}
System.out.println(transferred.get() + " bytes read from device");
return buffer;
}
/**
* Main method.
*/
public static void main(String[] args) throws Exception
{
// Initialize the libusb context

int result = LibUsb.init(null);
if (result != LibUsb.SUCCESS)
{
    System.out.println("ssss");
throw new LibUsbException("Unable to initialize libusb", result);
}
else
{
    System.out.println("/*/***");
}
// Open test device (Samsung Galaxy Nexus)
DeviceHandle handle = LibUsb.openDeviceWithVidPid(null, VENDOR_ID,PRODUCT_ID);
if (handle == null)
{
System.err.println("--Test device not found.");
System.exit(1);
}
else
{
    System.out.println("test devise found");
}
// Claim the ADB interface
result = LibUsb.detachKernelDriver(handle, interfaceNum);
if (result != LibUsb.SUCCESS)
{
throw new LibUsbException("Unable to claim interface", result);
}
// Send ADB CONNECT message
write(handle, CONNECT_HEADER);
System.out.println("connecteeee");
write(handle, CONNECT_BODY);
System.out.println("connbbbbbbb");

// Receive the header of the ADB answer (Most likely an AUTH message)
ByteBuffer header = read(handle, 24);
header.position(12);
int dataSize = header.asIntBuffer().get();
// Receive the body of the ADB answer
@SuppressWarnings("unused")
ByteBuffer data = read(handle, dataSize);
// Release the ADB interface
result = LibUsb.releaseInterface(handle, INTERFACE);
if (result != LibUsb.SUCCESS)
{
throw new LibUsbException("Unable to release interface", result);
}
// Close the device
LibUsb.close(handle);
// Deinitialize the libusb context
LibUsb.exit(null);
}
}

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
