### ISSUE TITLE
Typo in FAQ 

### ISSUE THREAD

**Issue by garroadran** [usb4java/usb4java#63]
**Bug description**
I'm not sure if this is the right place to report it, but there is a minor typo in the [FAQ](http://usb4java.org/faq.html) section of the website.

>   ```
> SUBSYSTEM=="usb",ATTR{idVendor}=="89ab",ATTR{idProduct}=="4567",MODE="0660",GROUP="plugdev"
> ```
> This means that whenever a USB device with vendor id 0x89ab and product id 0x4567 is attached then the group **wheel** is permitted to write to the device.

**Expected behavior**
I believe **wheel** should read "plugdev" in order to be consistent with the sample file content.

**Comment by kayahr** [comment]
Correct. In older Debian versions it was *wheel*, now it is *plugdev* so I changed it in the FAQ but missed the second occurrence. Is fixed now, thanks.
